# Generated by Django 6.1 on 2026-09-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('registrations', '0005_add_vendor_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='vendor_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='registrations.vendorregistration'),
        ),
    ]
