# Generated by Django 6.1 on 2026-09-11 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('entry_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_extra_fee', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['entry_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age_range', models.CharField(blank=True, choices=[('Under 18', 'Under 18'), ('18-29', '18-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60+', '60+')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('t_shirt_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=10)),
                ('division', models.CharField(blank=True, choices=[('mens-open', "Men's Open"), ('womens-open', "Women's Open"), ('corporate', 'Corporate'), ('masters', 'Masters')], max_length=20)),
                ('town_or_city', models.CharField(blank=True, max_length=150)),
                ('club_or_institution', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('medical_notes', models.TextField(blank=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'entry_type': 'INDIVIDUAL'}, on_delete=django.db.models.deletion.PROTECT, related_name='individual_registrations', to='registrations.category')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.participant')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=200)),
                ('company_or_institution', models.CharField(max_length=200)),
                ('relay_category', models.CharField(choices=[('mens-team', "Men's Team"), ('womens-team', "Women's Team"), ('mixed-team', 'Mixed Team')], max_length=20)),
                ('captain_first_name', models.CharField(max_length=150)),
                ('captain_last_name', models.CharField(max_length=150)),
                ('captain_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('captain_phone', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('auth_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('free_runner_limit', models.PositiveIntegerField()),
                ('accepted_terms', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'entry_type': 'TEAM', 'is_extra_fee': False}, on_delete=django.db.models.deletion.PROTECT, related_name='team_registrations', to='registrations.category')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterRunner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('covered', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='registrations.teamregistration')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
