# Generated by Django 6.1 on 2026-09-17 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_update_race_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='entry_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('TEAM', 'Team'), ('VENDOR', 'Vendor')], max_length=20),
        ),
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], default='PENDING_PAYMENT', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('contact_phone', models.CharField(max_length=30)),
                ('business_location', models.CharField(blank=True, max_length=200)),
                ('products_services', models.TextField(blank=True)),
                ('requirement', models.CharField(blank=True, choices=[('exhibition-space', 'Exhibition Space'), ('vendor-stall', 'Vendor Stall'), ('food-beverage-stall', 'Food & Beverage Stall'), ('corporate-activation', 'Corporate Activation'), ('branding-promotional', 'Branding / Promotional Space'), ('other', 'Other')], max_length=30)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'entry_type': 'VENDOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_registrations', to='registrations.category')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
