# Generated by Django 6.1 on 2026-09-11 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=30)),
                ('payment_method', models.CharField(choices=[('MTN_MONEY', 'MTN Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ZAMTEL_KWACHA', 'Zamtel Kwacha'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], max_length=30)),
                ('billing_details', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('individual_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.individualregistration')),
                ('roster_runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.rosterrunner')),
                ('team_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.teamregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('individual_registration__isnull', False), ('roster_runner__isnull', True), ('team_registration__isnull', True)), models.Q(('individual_registration__isnull', True), ('roster_runner__isnull', True), ('team_registration__isnull', False)), models.Q(('individual_registration__isnull', True), ('roster_runner__isnull', False), ('team_registration__isnull', True)), _connector='OR'), name='payment_exactly_one_target')],
            },
        ),
    ]
