# Generated by Django 6.1 on 2026-09-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_withdrawal'),
        ('registrations', '0005_add_vendor_registration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_exactly_one_target',
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.vendorregistration'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('individual_registration__isnull', False), ('team_registration__isnull', True), ('vendor_registration__isnull', True)), models.Q(('individual_registration__isnull', True), ('team_registration__isnull', False), ('vendor_registration__isnull', True)), models.Q(('individual_registration__isnull', True), ('team_registration__isnull', True), ('vendor_registration__isnull', False)), _connector='OR'), name='payment_exactly_one_target'),
        ),
    ]
